### ISSUE TITLE
Allow users to review selected files and enter extra metadata such as human readable description 

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-deposit-ui#21]

**Comment by jabrah** [comment]
This ticket represents part of the "file picker" part of the workflow Files step. This can be developed separately from the OneDrive file picker.

* [ ] Display list of pending files
* [ ] For each file:
  * [ ] Enter human readable metadata such as description
  * [ ] Get more metadata automatically such as checksum, filename, file size, etc
  * [ ] Ability to remove pending file or cancel its upload and otherwise prevent association with the submission
